/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brasiltur;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private ControlePassageiro cp;
    private ControleGaragem cg;
    private CadastroP cadastro_novo;
    private CadastroV cadastro_viagens;
    private CadastrarPassageiroNaViagem cadastro_pv;
    private MostrarPassageiros passageiros;
    private MostrarViagens viagens;
    private MostrarPV consultas;
    
    public JanelaPrincipal() {
        initComponents();
        cadastro_novo=new CadastroP();
        cadastro_viagens = new CadastroV();
        cadastro_pv = new CadastrarPassageiroNaViagem();
        passageiros = new MostrarPassageiros();
        viagens = new MostrarViagens();
        consultas = new MostrarPV();
        cp = new ControlePassageiro(); 
        cg = new ControleGaragem();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        TelaPreta = new javax.swing.JDesktopPane();
        carregarpassageiros = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        cadastropassageiro = new javax.swing.JMenuItem();
        cadastroviagem = new javax.swing.JMenuItem();
        cadastropv = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        consultar = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrasilTur");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        TelaPreta.setBackground(new java.awt.Color(255, 255, 255));

        carregarpassageiros.setText("Carregar");
        carregarpassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarpassageirosActionPerformed(evt);
            }
        });

        jLabel1.setText("Passageiros cadastrados");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("BrasilTur");

        jLabel3.setText("Carregue os módulos abaixo para verificar se existe eventual erro no programa");

        jLabel4.setText("Viagens cadastradas");

        jButton1.setText("Carregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel5.setText("Bem-vindo ao sistema de gerenciamento de viagem de turismo!");

        jLabel6.setText("Alan Ferreira, Beatriz Siqueira,");

        jLabel7.setText("Lucas Loscheider e Pedro Henrique.");

        jLabel8.setText("Desenvolvido por:");

        jLabel9.setText("Funções disponíveis:");

        jLabel10.setText("- Cadastramento de passageiros e viagens no sistema.");

        jLabel11.setText("- Visualizar passageiros e ônibus cadastrados no sistema.");

        jLabel12.setText("- Consultar informações de viagens.");

        jLabel13.setText("Atenção operador:");

        jLabel14.setText("Evite travamentos do sistema, não tente abrir a mesma janela 2 vezes.");

        jLabel15.setText("Faça backup manual dos arquivos que armazenam informações, disponíveis na pasta principal do programa.");

        jLabel16.setText("Suporte 24h no telefone 0800 3698 5214 .");

        jLabel17.setText("ID de venda: 987865453212");

        TelaPreta.setLayer(carregarpassageiros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaPreta.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaPretaLayout = new javax.swing.GroupLayout(TelaPreta);
        TelaPreta.setLayout(TelaPretaLayout);
        TelaPretaLayout.setHorizontalGroup(
            TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPretaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator2)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPretaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPretaLayout.createSequentialGroup()
                        .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TelaPretaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(TelaPretaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPretaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPretaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(354, 354, 354))))
            .addGroup(TelaPretaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(TelaPretaLayout.createSequentialGroup()
                        .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaPretaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carregarpassageiros))
                            .addGroup(TelaPretaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(jButton1))
                            .addComponent(jLabel3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(TelaPretaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaPretaLayout.setVerticalGroup(
            TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPretaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(carregarpassageiros))
                .addGap(18, 18, 18)
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17))
                .addGap(9, 9, 9))
        );

        getContentPane().add(TelaPreta);
        TelaPreta.setBounds(0, 0, 820, 530);

        cadastro.setText("Cadastrar");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        cadastropassageiro.setText("Cadastro Passageiro no Sistema");
        cadastropassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastropassageiroActionPerformed(evt);
            }
        });
        cadastro.add(cadastropassageiro);

        cadastroviagem.setText("Cadastro Viagem/ônibus");
        cadastroviagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroviagemActionPerformed(evt);
            }
        });
        cadastro.add(cadastroviagem);

        cadastropv.setText("Cadastro Passageiro na Viagem");
        cadastropv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastropvActionPerformed(evt);
            }
        });
        cadastro.add(cadastropv);

        jMenuBar1.add(cadastro);

        jMenu1.setText("Visualizar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Passageiros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Viagens");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        consultar.setText("Consultar Viagens");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        consultar.add(jMenuItem3);

        jMenuBar1.add(consultar);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 835, 592);
    }// </editor-fold>//GEN-END:initComponents

    public CadastroP getCadastro_novo() {
        return cadastro_novo;
    }

    public void setCadastro_novo(CadastroP cadastro_novo) {
        this.cadastro_novo = cadastro_novo;
    }

    public CadastroV getCadastro_viagens() {
        return cadastro_viagens;
    }

    public void setCadastro_viagens(CadastroV cadastro_viagens) {
        this.cadastro_viagens = cadastro_viagens;
    }

    public CadastrarPassageiroNaViagem getCadastro_pv() {
        return cadastro_pv;
    }

    public void setCadastro_pv(CadastrarPassageiroNaViagem cadastro_pv) {
        this.cadastro_pv = cadastro_pv;
    }

    public JMenuItem getCadastropassageiro() {
        return cadastropassageiro;
    }

    public void setCadastropassageiro(JMenuItem cadastropassageiro) {
        this.cadastropassageiro = cadastropassageiro;
    }

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
       
    }//GEN-LAST:event_cadastroActionPerformed

    private void cadastropassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastropassageiroActionPerformed
       
        TelaPreta.add(cadastro_novo);
        cadastro_novo.setVisible(true);
    }//GEN-LAST:event_cadastropassageiroActionPerformed

    private void cadastroviagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroviagemActionPerformed
         
         TelaPreta.add(cadastro_viagens);
         cadastro_viagens.setVisible(true);
    }//GEN-LAST:event_cadastroviagemActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed

    }//GEN-LAST:event_consultarActionPerformed

    private void cadastropvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastropvActionPerformed
       
        TelaPreta.add(cadastro_pv);
        cadastro_pv.setVisible(true);
    }//GEN-LAST:event_cadastropvActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            TelaPreta.add(passageiros);
            passageiros.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void carregarpassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarpassageirosActionPerformed
        if(!cp.carregarArquivo()){
            carregarpassageiros.setText("Carregar novamente");
            JOptionPane.showMessageDialog(null, "Erro ao carregar arquivo!");
            carregarpassageiros.setEnabled(true);
        }else{
            carregarpassageiros.setText("Carregado");
            carregarpassageiros.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Modulo carregado com sucesso!");             
            cp.relacaoPassageiros();
        }
    }//GEN-LAST:event_carregarpassageirosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            TelaPreta.add(viagens);
            viagens.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!cg.carregarArquivo()){
            jButton1.setText("Carregar novamente");
            JOptionPane.showMessageDialog(null, "Erro ao carregar arquivo!");
            jButton1.setEnabled(true);
        }else{
            jButton1.setText("Carregado");
            jButton1.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Modulo carregado com sucesso!");             
            cg.relacaoOnibus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaPreta.add(consultas);
        consultas.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane TelaPreta;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem cadastropassageiro;
    private javax.swing.JMenuItem cadastropv;
    private javax.swing.JMenuItem cadastroviagem;
    private javax.swing.JToggleButton carregarpassageiros;
    private javax.swing.JMenu consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
